/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package launch

import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Group
import javafx.scene.Scene
import javafx.scene.canvas.Canvas
import javafx.scene.image.Image
import javafx.scene.layout.StackPane
import javafx.scene.layout.VBox
import javafx.stage.Stage
import java.io.InputStream

class App: Application() {
    private val width = 800.0
    private val height = 600.0
    private val resize = false
    private val title = "宠物王国 紫"
    private val canvas = Canvas(400.0,400.0)
    private val gc = canvas.graphicsContext2D

    override fun start(primaryStage: Stage?) {


        val layout = StackPane()
//        val img = Image(load("../img/98.png"))
        val bg = Image(load("/img/background.png"))
//        gc.drawImage(img,img.width,img.height)
        gc.drawImage(bg,bg.width,bg.height)

        val vBox = VBox()
        val root = Group()

        vBox.children.addAll(canvas)
        root.children.add(vBox)
        layout.children.add(root)


        // 初始化
        primaryStage!!.title = title
        val scene = Scene(layout, 800.0, 600.0)

        primaryStage.scene = scene
        primaryStage.isResizable = resize
        primaryStage.show()
    }

    private fun load(path: String): InputStream {
        return this.javaClass.getResourceAsStream(path)!!
    }
}


fun main(args: Array<String>) {
    launch(App::class.java,*args)
}
